local_costmap:
   global_frame: odom
   robot_base_frame: base_footprint
   update_frequency: 10
   publish_frequency: 4
   width: 6.0
   height: 6.0
   resolution: 0.01
   static_map: false
   rolling_window: true
